version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "4000:4000"
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
