version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    #environment:
    # command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

volumes:
  redis-data:
    driver: local
